include:
  - project: "trixgo-vn/devops/gitlab-ci-template"
    file: "/.Docker.gitlab-ci.yml"

build-docker-staging:
  extends: .build-docker-template
  before_script:
    - _DOCKER_CACHE_IMAGE_TAG=`echo $CI_COMMIT_REF_NAME | sed -E 's/[^a-z0-9._-]+/__/g'`
    - _DOCKER_RELEASE_IMAGE_TAG="$_DOCKER_CACHE_IMAGE_TAG-`printf %010d $CI_PIPELINE_ID`-$CI_COMMIT_SHORT_SHA"
    - |
      cat <<EOF > .env.production
      NEXT_PUBLIC_API_MODE=mock
      NEXT_PUBLIC_API_URL=https://api.trixgo.com
      NEXT_PUBLIC_API_TIMEOUT=30000
      NEXT_PUBLIC_CLOUDFRONT_URL=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_IMAGE_PREFIX=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_DEFAULT_TOKEN=$NEXT_PUBLIC_DEFAULT_TOKEN
      NEXT_PUBLIC_OPENAI_API_KEY=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
      ANALYZE=false
      NEXT_PUBLIC_ASSISTANT_ID=asst_J0yv4aAeR1sd52nDWd2ERfh7
      NEXT_PUBLIC_VECTOR_STORE_ID=vs_682dbb33cf10819183915530265036a5
      EOF
  tags:
    - docker-xlarge
  only:
    refs:
      - staging

build-docker-prod:
  extends: .build-docker-template
  before_script:
    - _DOCKER_CACHE_IMAGE_TAG=`echo $CI_COMMIT_REF_NAME | sed -E 's/[^a-z0-9._-]+/__/g'`
    - _DOCKER_RELEASE_IMAGE_TAG="$_DOCKER_CACHE_IMAGE_TAG-`printf %010d $CI_PIPELINE_ID`-$CI_COMMIT_SHORT_SHA"
    - |
      cat <<EOF > .env.production
      NEXT_PUBLIC_API_MODE=mock
      NEXT_PUBLIC_API_URL=https://api.trixgo.com
      NEXT_PUBLIC_API_TIMEOUT=30000
      NEXT_PUBLIC_CLOUDFRONT_URL=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_IMAGE_PREFIX=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_DEFAULT_TOKEN=$NEXT_PUBLIC_DEFAULT_TOKEN
      NEXT_PUBLIC_OPENAI_API_KEY=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
      ANALYZE=false
      NEXT_PUBLIC_ASSISTANT_ID=asst_J0yv4aAeR1sd52nDWd2ERfh7
      NEXT_PUBLIC_VECTOR_STORE_ID=vs_682dbb33cf10819183915530265036a5
      EOF
  tags:
    - docker-xlarge
  only:
    refs:
      - main
