include:
  - project: "trixgo-vn/devops/gitlab-ci-template"
    file: "/.Docker.gitlab-ci.yml"

build-docker-staging:
  extends: .build-docker-template
  before_script:
    - _DOCKER_CACHE_IMAGE_TAG=`echo $CI_COMMIT_REF_NAME | sed -E 's/[^a-z0-9._-]+/__/g'`
    - _DOCKER_RELEASE_IMAGE_TAG="$_DOCKER_CACHE_IMAGE_TAG-`printf %010d $CI_PIPELINE_ID`-$CI_COMMIT_SHORT_SHA"
    - |
      cat <<EOF > .env.production
      NEXT_PUBLIC_API_MODE=mock
      NEXT_PUBLIC_API_URL=https://api.trixgo.com
      NEXT_PUBLIC_API_TIMEOUT=30000
      NEXT_PUBLIC_CLOUDFRONT_URL=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_IMAGE_PREFIX=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_DEFAULT_TOKEN=$NEXT_PUBLIC_DEFAULT_TOKEN
      NEXT_PUBLIC_OPENAI_API_KEY=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
      EOF
  tags:
    - docker-xlarge
  only:
    refs:
      - staging

build-docker-prod:
  extends: .build-docker-template
  before_script:
    - _DOCKER_CACHE_IMAGE_TAG=`echo $CI_COMMIT_REF_NAME | sed -E 's/[^a-z0-9._-]+/__/g'`
    - _DOCKER_RELEASE_IMAGE_TAG="$_DOCKER_CACHE_IMAGE_TAG-`printf %010d $CI_PIPELINE_ID`-$CI_COMMIT_SHORT_SHA"
    - |
      cat <<EOF > .env.production
      NEXT_PUBLIC_API_MODE=mock
      NEXT_PUBLIC_API_URL=https://api.trixgo.com
      NEXT_PUBLIC_API_TIMEOUT=30000
      NEXT_PUBLIC_CLOUDFRONT_URL=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_IMAGE_PREFIX=https://dntdurzwr12tp.cloudfront.net
      NEXT_PUBLIC_DEFAULT_TOKEN=$NEXT_PUBLIC_DEFAULT_TOKEN
      NEXT_PUBLIC_OPENAI_API_KEY=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
      EOF
  tags:
    - docker-xlarge
  only:
    refs:
      - main
