name: Trigger build docker on push
on:
  push:
    branches:
      - staging
      - main
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: curl
        run: |
          apk add curl bash
          IMAGE_TAG="${{ github.ref_name }}-${{ github.run_id }}-${GITHUB_SHA::7}"
          curl -f -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CI_PAT }}" \
            https://api.github.com/repos/szen7dev/trixgo-builds/actions/workflows/website.yml/dispatches \
            -d "{\"ref\": \"main\", \"inputs\": {\"REF\": \"${{ github.sha }}\", \"IMAGE_TAG\": \"$IMAGE_TAG\"}}"